// Generated by CoffeeScript 1.9.2
(function() {
  var base64, bldCSSPath, bldImgPath, bldJSPath, bldLibPath, bldPath, bldResourcePath, bldViewsPath, compass, devCSSPath, devImgPath, devJSPath, devLibPath, devPath, devResourcePath, devSassPath, devViewsPath, eol, eolFile, gulp, livereload, minifyCSS, minifyHTML, rename, uglify;

  gulp = require('gulp');

  eol = require('gulp-eol');

  rename = require('gulp-rename');

  minifyCSS = require('gulp-minify-css');

  minifyHTML = require('gulp-minify-html');

  uglify = require('gulp-uglify');

  compass = require('gulp-compass');

  base64 = require('gulp-base64');

  livereload = require('gulp-livereload');

  devPath = 'src/develop';

  devViewsPath = devPath + "/views";

  devResourcePath = devPath + "/public";

  devSassPath = devResourcePath + "/sass";

  devCSSPath = devResourcePath + "/css";

  devJSPath = devResourcePath + "/js";

  devLibPath = devResourcePath + "/lib";

  devImgPath = devResourcePath + "/img";

  bldPath = 'src/build';

  bldViewsPath = bldPath + "/views";

  bldResourcePath = bldPath + "/public";

  bldCSSPath = bldResourcePath + "/css";

  bldJSPath = bldResourcePath + "/js";

  bldLibPath = bldResourcePath + "/lib";

  bldImgPath = bldResourcePath + "/img";

  eolFile = function(filePath, destPath) {
    console.log("eolFile filePath: " + filePath);
    return gulp.src(filePath).pipe(eol('\n')).pipe(gulp.dest(destPath));
  };

  gulp.task('compass', function() {
    return gulp.src(devSassPath + "\/*.scss").pipe(compass({
      css: devCSSPath,
      sass: devSassPath
    })).on('error', function(error) {
      console.log(error);
      return this.emit('end');
    });
  });

  gulp.task('watch-compass', function() {
    gulp.watch(devSassPath + "\/*.scss", ['compass']);
    return gulp.watch(devCSSPath + "\/*.css", function(obj) {
      return eolFile(obj.path, devCSSPath);
    });
  });

  gulp.task('eol-css', ['compass'], function() {
    return eolFile(devCSSPath + "\/*.css", devCSSPath);
  });

  gulp.task('watch', ['watch-compass'], function() {
    livereload.listen();
    return gulp.watch([devViewsPath + "\/**\/*.*", devJSPath + "\/**\/*.*", devCSSPath + "\/**\/*.*", devImgPath + "\/**\/*.*"], function(file) {
      return livereload.changed(file.path);
    });
  });

  gulp.task('build', function() {
    gulp.src(devCSSPath + "\/*.css").pipe(base64({
      extensions: [/#tobase64"?$/i]
    })).pipe(minifyCSS()).pipe(gulp.dest(bldCSSPath));
    gulp.src(devJSPath + "\/**\/*.js").pipe(uglify()).pipe(gulp.dest(bldJSPath));
    gulp.src(devImgPath + "\/**\/*.*").pipe(gulp.dest(bldImgPath));
    gulp.src(devViewsPath + "\/**\/*.ejs").pipe(gulp.dest(bldViewsPath));
    return gulp.src([devLibPath + "\/**\/*", devLibPath + "\/**\/.*"]).pipe(gulp.dest(bldLibPath));
  });

}).call(this);
