// Generated by CoffeeScript 1.9.2
(function() {
  var async, fs, path;

  async = require('async');

  fs = require('fs');

  path = require('path');

  module.exports = {
    index: function(req, res, next) {
      var base;
      base = {
        title: 'Home Page',
        keywords: "",
        description: ""
      };
      return res.render('index', {
        base: base
      });
    }
  };

}).call(this);
